/*
-- Query: SELECT * FROM constructelite.project
LIMIT 0, 1000

-- Date: 2024-05-22 00:20
*/
INSERT INTO constructelite.project (`project_id`,`budget`,`created_at`,`land_size`,`location`,`name`,`project_description`,`timeline`,`client_id`,`sp_id`) VALUES (5,'30 lakh','2024-04-13 08:40:49.255049','2 acre','kothrud','ved Home 1','<p>This project is created by&nbsp;</p>\r\n<p><strong>Vedika Kandekar</strong> User</p>\r\n<p>All the details will be stored here about this document</p>\r\n<p>expectations:</p>\r\n<p>budget breakdown in detail ,<s> what vedika wants in project ...etc</s></p>','6 months',18,NULL);
INSERT INTO constructelite.project (`project_id`,`budget`,`created_at`,`land_size`,`location`,`name`,`project_description`,`timeline`,`client_id`,`sp_id`) VALUES (6,'10 lakhs','2024-04-13 08:42:33.411215','7 guntha','kharadi','vedika Project 2','<p>this Project is also created by :</p>\r\n<p style=\"text-align: center;\"><strong>Vedika Kandekar </strong>client</p>\r\n<p style=\"text-align: center;\">&nbsp;</p>\r\n<p style=\"text-align: right;\">Thank You.</p>','3 months',18,NULL);
INSERT INTO constructelite.project (`project_id`,`budget`,`created_at`,`land_size`,`location`,`name`,`project_description`,`timeline`,`client_id`,`sp_id`) VALUES (7,'5 crore','2024-04-13 08:44:44.562764','3 acre','Mumbai','Shraddha Home1','<p>This project is created by<strong> Shraddha ,</strong></p>\r\n<p><strong>All details are explained here...</strong></p>\r\n<p>&nbsp;</p>','1 year',19,NULL);
INSERT INTO constructelite.project (`project_id`,`budget`,`created_at`,`land_size`,`location`,`name`,`project_description`,`timeline`,`client_id`,`sp_id`) VALUES (8,'20 crore','2024-04-13 08:46:04.404366','10 acre','Delhi','Shraddha Building','<p>This is a cluster of dream buildings of&nbsp;</p>\r\n<p style=\"text-align: right;\"><strong>created by shraddha</strong></p>','1 year',19,NULL);
INSERT INTO constructelite.project (`project_id`,`budget`,`created_at`,`land_size`,`location`,`name`,`project_description`,`timeline`,`client_id`,`sp_id`) VALUES (10,'2 crore','2024-04-15 22:24:15.523369','2 acre','Bandra','Ved Dream Home','<p>project by ved: <strong>Dream Home</strong></p>\r\n<p>..</p>\r\n<p>..</p>\r\n<p>..</p>','1 year',18,NULL);
